name: CI

on:
  push:
      branches: [main,workflow]
  workflow_dispatch:
    

defaults:
  run:
    shell: bash
    working-directory: ./nocom/


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
